// client/vue3-tsx/src/components/switch/Switch.tsx
import { computed, defineComponent } from 'vue'
import './Switch.scss'

export default defineComponent({
  name: 'Switch',
  props: {
    modelValue: {
      type: Boolean
    },
    onText: {
      type: String,
      default: '开'
    },
    offText: {
      type: String,
      default: '关'
    },
    onLeverBgColor: {
      type: String,
      default: '#6bc30d'
    },
    offLeverBgColor: {
      type: String,
      default: '#fdfdfd'
    },
    onTextColor: {
      type: String,
      default: '#6bc30d'
    },
    offTextColor: {
      type: String,
      default: '#6bc30d'
    },
    onBgColor: {
      type: String,
      default: '#fdfdfd'
    },
    offBgColor: {
      type: String,
      default: '#fdfdfd'
    },
    onValue: {
      type: Boolean,
      default: true
    },
    offValue: {
      type: Boolean,
      default: false
    },
    disabled: Boolean,
    labelText: String
  },
  emits: ['update:modelValue'],
  setup (props, { emit }) {
    const checked = computed(() => props.modelValue)

    const leverStyle = computed(() => {
      return { backgroundColor: checked.value ? props.onLeverBgColor : props.offLeverBgColor }
    })

    const switchStyle = computed(() => {
      return {
        color: checked.value ? props.onTextColor : props.offTextColor,
        backgroundColor: checked.value ? props.onBgColor : props.offBgColor
      }
    })

    function handleChange (e: any) {
      emit('update:modelValue', e.target.checked ? props.onValue : props.offValue)
    }

    return () => (
      <div class="mt-switch">
        <label>
          <span class="mt-switch__text">
            <slot>{ props.labelText }</slot>
          </span>
          <input
            checked={props.modelValue}
            type="checkbox"
            disabled={props.disabled}
            onInput={handleChange}
          />
          <div
            class="mt-switch__lever"
            style={leverStyle.value}
          >
            <span
              class={checked.value ? 'mt-switch__on' : 'mt-switch__off'}
              style={switchStyle.value}
            >
              { checked.value ? props.onText : props.offText }
            </span>
          </div>
        </label>
      </div>
    )
  }
})

// client/react/src/components/switch/switch.component.tsx
import { ChangeEvent, ChangeEventHandler, FC, useEffect, useState } from 'react'

import './switch.styles.scss'

interface SwitchProps {
  value: boolean
  labelText?: string
  onText?: string // 开关文本
  offText?: string
  onLeverBgColor?: string // 杠杆背景色
  offLeverBgColor?: string
  onTextColor?: string // 开关文字颜色
  offTextColor?: string
  onBgColor?: string // 开关背景色
  offBgColor?: string
  disabled?: boolean
  onChange?: (event: ChangeEvent<HTMLInputElement>) => void
}

const ON_COLOR = '#6bc30d'
const OFF_COLOR = '#fdfdfd'

const Switch: FC<SwitchProps> = ({
  value,
  labelText,
  onText = '开',
  offText = '关',
  onLeverBgColor = ON_COLOR,
  offLeverBgColor = OFF_COLOR,
  onTextColor = ON_COLOR,
  offTextColor = ON_COLOR,
  onBgColor = OFF_COLOR,
  offBgColor = OFF_COLOR,
  disabled = false,
  onChange
}) => {
  // state
  const [checked, setChecked] = useState(value)
  const [switchStyle, setSwitchStyle] = useState({})

  // handlers
  const handleChange: ChangeEventHandler<HTMLInputElement> = (event) => {
    setChecked(event.target.checked)
    onChange && onChange(event)
  }

  // hooks
  useEffect(() => {
    setSwitchStyle({
      color: checked ? onTextColor : offTextColor,
      backgroundColor: checked ? onBgColor : offBgColor
    })
  }, [checked, onTextColor, offTextColor, onBgColor, offBgColor])

  return (
    <div className="switch">
      <label>
        <span className="switch-text">{labelText}</span>
        <input
          v-model="checked"
          type="checkbox"
          defaultChecked={checked}
          disabled={disabled}
          onChange={handleChange}
        />
        <div
          className="switch-lever"
          style={{
            backgroundColor: checked ? onLeverBgColor : offLeverBgColor
          }}
        >
          <span
            className={checked ? 'switch-on' : 'switch-off'}
            style={switchStyle}
          >
            {checked ? onText : offText}
          </span>
        </div>
      </label>
    </div>
  )
}

export default Switch
