// client/react/src/routes/player/player.component.tsx
import {
  GoStart,
  GoEnd,
  Play,
  PauseOne,
  VolumeMute,
  VolumeSmall,
  VolumeNotice,
  PlayCycle,
  ShuffleOne,
  PlayOnce
} from '@icon-park/react'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Link } from 'react-router-dom'

import './player.styles.scss'
import useCd from './useCd'
import useMode from './useMode'
import IconPark from '@/components/icon-park/icon-park.component'
import ProgressBar from '@/components/progress-bar/progress-bar.component'
import { selectCurrentSong, selectPlayerReducer } from '@/store/selectors'
import {
  setCurrentTime,
  setPlaying,
  setProgressChanging,
  setVolume
} from '@/store/slices/player'
import { formatTime } from '@/utils'
import emitter from '@/utils/emitter'
import { PLAY_MODE } from '@/utils/enums'

const Player = () => {
  // selectors
  const currentSong = useSelector(selectCurrentSong)
  const { playing, currentTime, volume } = useSelector(selectPlayerReducer)

  // dispatch
  const dispatch = useDispatch()
  const _setProgressChanging = (progressChanging: boolean) =>
    dispatch(setProgressChanging(progressChanging))
  const _setCurrentTime = (currentTime: number) =>
    dispatch(setCurrentTime(currentTime))
  const _setPlaying = (playing: boolean) => dispatch(setPlaying(playing))
  const _setVolume = (volume: number) => dispatch(setVolume(volume))

  // state
  const [progress, setProgress] = useState(0)

  // handlers
  const prev = () => emitter.emit('prev')
  const next = () => emitter.emit('next')
  const onProgressChanging = (progress: number) => {
    _setProgressChanging(true)
    _setCurrentTime(currentSong.duration! * progress)
  }
  const onProgressChanged = (progress: number) => {
    _setProgressChanging(false)
    if (currentSong.duration) {
      const currentTime = currentSong.duration * progress
      _setCurrentTime(currentTime)
      // 更新 audio 当前播放时间
      emitter.emit('changeTime', currentTime)
    }
    if (!playing) {
      _setPlaying(true)
    }
  }
  const onVolumeChange = (volume: number) => {
    _setVolume(volume)
    // 更新 audio 音量
    emitter.emit('changeVolume', volume)
  }
  const togglePlay = () => {
    _setPlaying(!playing)
  }

  // hooks
  const { playMode, changeMode } = useMode()
  const { cdRef, cdCoverRef, cdClass } = useCd()

  useEffect(() => {
    const duration = currentSong?.duration ?? 0
    setProgress(currentTime / duration)
  }, [currentSong, currentTime])

  return (
    <div className="mt-8 sm:mt-28">
      <h1 className="player-title">
        <Link to="/musics">我的私人音乐坊 &gt;</Link>
      </h1>
      <div className="flex items-center mt-6 flex-col-reverse sm:flex-row">
        <div className="flex-1 w-full">
          <div className="flex items-center h-9 mt-6 justify-center sm:mt-0 sm:justify-start">
            <span className="text-xl text-gray-800 text">
              {currentSong?.title}
            </span>
            <span className="text-sm text-gray-600 ml-1">
              <i className="mx-1.5.5.5.5.5">-</i> {currentSong?.artist}
            </span>
          </div>
          <div className="flex items-center mt-8">
            <span className="player-music-time mr-1.5">
              {formatTime(currentTime)}
            </span>
            <div className="flex-1">
              <ProgressBar
                progress={progress}
                onProgressChanging={onProgressChanging}
                onProgressChanged={onProgressChanged}
              />
            </div>
            <span className="player-music-time ml-1.5">
              {formatTime(currentSong?.duration)}
            </span>
          </div>
          <div className="player-control flex items-center justify-between mt-10">
            <IconPark
              component={
                playMode === PLAY_MODE.SEQUENCE
                  ? PlayCycle
                  : playMode === PLAY_MODE.RANDOM
                  ? ShuffleOne
                  : PlayOnce
              }
              size={28}
              onClick={changeMode}
            />
            <span className="inline-flex items-center">
              <IconPark component={GoStart} onClick={prev} />
              <IconPark
                component={playing ? PauseOne : Play}
                className="ml-5"
                size={40}
                onClick={togglePlay}
              />
              <IconPark component={GoEnd} className="ml-5" onClick={next} />
            </span>
            <div className="inline-flex items-center ">
              <IconPark
                component={
                  volume === 0
                    ? VolumeMute
                    : volume < 0.3
                    ? VolumeSmall
                    : VolumeNotice
                }
                size={16}
              />
              <div className="w-16 ml-1.5">
                <ProgressBar
                  progress={volume}
                  onProgressChanging={onVolumeChange}
                  onProgressChanged={onVolumeChange}
                />
              </div>
            </div>
          </div>
        </div>
        <div className="w-[180px] h-[180px] sm:ml-5">
          {currentSong && (
            <div ref={cdRef}>
              <img
                ref={cdCoverRef}
                className={`w-full h-full rounded-full ${cdClass}`}
                src={currentSong.cover}
                alt={currentSong.title}
              />
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default Player

// client/vue3-tsx/src/views/player/Player.tsx
import {
  VolumeMute,
  VolumeSmall,
  VolumeNotice,
  PauseOne,
  Play,
  GoStart,
  GoEnd
} from '@icon-park/vue-next'
import { computed, defineComponent } from 'vue'
import './Player.scss'
import useCd from './useCd'
import useMode from './useMode'
import ProgressBar from '@/components/progress-bar/ProgressBar'
import { usePlayerStore } from '@/store/player'
import { formatTime } from '@/utils'
import emitter from '@/utils/emitter'

export default defineComponent({
  name: 'Player',
  setup () {
    // store
    const playerStore = usePlayerStore()
    const playing = computed(() => playerStore.playing)
    const currentSong = computed(() => playerStore.currentSong)
    const currentTime = computed(() => playerStore.currentTime)
    const volume = computed(() => playerStore.volume)

    // hooks
    const { currentMode, changeMode } = useMode()
    const { cdRef, cdCoverRef, cdClass } = useCd()

    // computed
    const PlayPause = computed(() => {
      return playing.value ? PauseOne : Play
    })
    const progress = computed(() => {
      const duration = currentSong.value?.duration ?? 0
      return currentTime.value / duration
    })
    const Volume = computed(() => {
      return volume.value === 0
        ? VolumeMute
        : volume.value < 0.3
          ? VolumeSmall
          : VolumeNotice
    })

    // methods
    const togglePlay = () => {
      playerStore.setPlaying(!playing.value)
    }

    const prev = () => emitter.emit('prev')
    const next = () => emitter.emit('next')

    const onProgressChanging = (progress: number) => {
      playerStore.setProgressChanging(true)
      playerStore.setCurrentTime(currentSong.value.duration! * progress)
    }
    const onProgressChanged = (progress: number) => {
      playerStore.setProgressChanging(false)

      const currentTime = currentSong.value.duration! * progress
      playerStore.setCurrentTime(currentTime)
      emitter.emit('changeTime', currentTime)

      if (!playing.value) {
        playerStore.setPlaying(true)
      }
    }

    const onVolumeChange = (volume: number) => {
      playerStore.setVolume(volume)
      emitter.emit('changeVolume', volume)
    }

    return () => (
      <div class="mt-8 sm:mt-28">
        <h1 class="player-title">
          <router-link to="/musics">我的私人音乐坊 &gt;</router-link>
        </h1>
        <div class="flex items-center mt-6 flex-col-reverse sm:flex-row">
          <div class="flex-1 w-full">
            <div class="flex items-center h-9 mt-6 justify-center sm:mt-0 sm:justify-start">
              <span class="text-xl text-gray-800 text">
                {currentSong.value?.title}
              </span>
              <span class="text-sm text-gray-600 ml-1">
                <i class="mx-1.5.5.5.5.5">-</i> {currentSong.value?.artist}
              </span>
            </div>
            <div class="flex items-center mt-8">
              <span class="music-time mr-1.5">
                {formatTime(currentTime.value)}
              </span>
              <ProgressBar
                class="flex-1"
                progress={progress.value}
                onProgressChanging={onProgressChanging}
                onProgressChanged={onProgressChanged}
              />
              <span class="music-time ml-1.5">
                {formatTime(currentSong.value?.duration)}
              </span>
            </div>
            <div class="player-control flex items-center justify-between mt-10">
              <currentMode.value
                class="cursor-pointer"
                theme="outline"
                size="28"
                stroke-width={3}
                fill="#4b5563"
                onClick={changeMode}
              />
              <span class="inline-flex items-center">
                <GoStart
                  class="cursor-pointer"
                  theme="outline"
                  size="32"
                  fill="#4b5563"
                  stroke-width={3}
                  onClick={prev}
                />
                <PlayPause.value
                  class="cursor-pointer ml-5"
                  theme="outline"
                  size="40"
                  fill="#4b5563"
                  stroke-width={3}
                  onClick={togglePlay}
                />
                <GoEnd
                  class="cursor-pointer ml-5"
                  theme="outline"
                  size="32"
                  fill="#4b5563"
                  stroke-width={3}
                  onClick={next}
                />
              </span>
              <div class="inline-flex items-center ">
                <Volume.value theme="outline" size="16" fill="#4b5563" />
                <div class="w-16 ml-1.5">
                  <ProgressBar
                    progress={volume.value}
                    onProgressChanging={onVolumeChange}
                    onProgressChanged={onVolumeChange}
                  />
                </div>
              </div>
            </div>
          </div>
          <div class="w-[180px] h-[180px] sm:ml-5">
            <div v-show="currentSong" ref={cdRef}>
              <img
                ref={cdCoverRef}
                class={'w-full h-full rounded-full ' + cdClass.value}
                src={currentSong.value?.cover}
                alt={currentSong.value?.title}
              />
            </div>
          </div>
        </div>
      </div>
    )
  }
})
