// client/vue3-tsx/src/layouts/footer/Footer.tsx
import { GithubOne } from '@icon-park/vue-next'
import { defineComponent } from 'vue'
import './Footer.scss'

export default defineComponent({
  name: 'Footer',
  setup () {
    return () => (
      <div class="footer">
        <a
          href="https://github.com/savoygu/music-player"
          target="_blank"
          title="Create by @savoygu"
        >
          <GithubOne
            theme="outline"
            size="24"
            fill="3"
          />
        </a>
      </div>
    )
  }
})

// client/react/src/components/footer/footer.component.tsx
import { GithubOne } from '@icon-park/react'
import { FC } from 'react'

import './footer.styles.scss'

interface FooterProps { }

const Footer: FC<FooterProps> = () => {
  return (
    <div className="footer">
      <a
        href="https://github.com/savoygu/music-player"
        target="_blank"
        title="Create by @savoygu" rel="noreferrer"
      >
        <GithubOne
          theme="outline"
          size="24"
          fill="3"
        />
      </a>
    </div>
  )
}

export default Footer
