// client/react/src/components/audio/audio.component.tsx
import { forwardRef, ForwardRefRenderFunction, ReactEventHandler, useImperativeHandle, useRef, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { useEffectOnce, useUpdateEffect } from 'react-use'

import {
  selectCurrentSong,
  selectPlayerReducer,
  selectPlayList
} from '@/store/selectors'
import {
  setCurrentIndex,
  setCurrentSongDuration,
  setCurrentTime,
  setPlaying,
  setVolume
} from '@/store/slices/player'
import { PLAY_MODE } from '@/utils/enums'

import './audio.styles.scss'

interface AudioProps { }
export type AudioRef = {
  prev: () => void
  next: () => void
  changeTime: (currentTime: number) => void
  changeVolume: (volume: number) => void
}

const Audio: ForwardRefRenderFunction<AudioRef, AudioProps> = (props, forwardedRef) => {
  // selectors
  const {
    playing,
    playMode,
    currentIndex,
    currentTime,
    progressChanging,
    volume
  } = useSelector(selectPlayerReducer)
  const playList = useSelector(selectPlayList)
  const currentSong = useSelector(selectCurrentSong)

  // dispatch
  const dispatch = useDispatch()
  const _setPlaying = (playing: boolean) => dispatch(setPlaying(playing))
  const _setCurrentSongDuration = (duration: number) =>
    dispatch(setCurrentSongDuration(duration))
  const _setVolume = (volume: number) => dispatch(setVolume(volume))
  const _setCurrentIndex = (index: number) => dispatch(setCurrentIndex(index))
  const _setCurrentTime = (currentTime: number) =>
    dispatch(setCurrentTime(currentTime))

  // state
  const audioRef = useRef<HTMLAudioElement>(null)
  const [isReady, setIsReady] = useState(false)

  // handlers
  const pause = () => {
    if (!playing) return

    _setPlaying(false)
  }

  const ready: ReactEventHandler<HTMLAudioElement> = (e) => {
    if (isReady) return
    setIsReady(true)

    const audioEl = e.target as HTMLAudioElement
    if (!currentSong.duration) {
      _setCurrentSongDuration(audioEl.duration)
    }
    _setVolume(audioEl.volume)
  }

  const loop = () => {
    if (!audioRef.current) return
    audioRef.current.currentTime = 0

    _setPlaying(true)
  }

  const prev = () => {
    const list = playList
    if (!isReady || !list.length) return
    if (list.length === 1) {
      loop()
    } else {
      let index = currentIndex - 1
      if (index === -1) index = list.length - 1
      _setCurrentIndex(index)

      if (!playing) _setPlaying(true)
    }
  }

  const next = () => {
    const list = playList
    if (!isReady || !list.length) return
    if (list.length === 1) {
      loop()
    } else {
      let index = currentIndex + 1
      if (index === list.length) index = 0
      _setCurrentIndex(index)

      if (!playing) _setPlaying(true)
    }
  }

  const error = () => {
    setIsReady(true)
  }

  const updateTime: ReactEventHandler<HTMLAudioElement> = (e) => {
    if (progressChanging || !playing) return

    _setCurrentTime((e.target as HTMLAudioElement).currentTime)
  }

  const changeTime = (currentTime: number) => {
    if (audioRef.current) {
      audioRef.current.currentTime = currentTime
    }
  }

  const end = () => {
    _setCurrentTime(0)

    if (playMode === PLAY_MODE.LOOP) {
      loop()
    } else {
      next()
    }
  }

  const changeVolume = (volume: number) => {
    if (audioRef.current) {
      audioRef.current.volume = volume
    }
  }

  // hooks
  useUpdateEffect(() => {
    if (!isReady) return

    const audioEl = audioRef.current!
    playing ? audioEl.play() : audioEl.pause()
  }, [playing])

  useUpdateEffect(() => {
    if (!currentSong.url) return
    setIsReady(false)

    const audioEl = audioRef.current!
    audioEl.src = currentSong.url
    audioEl.play()
  }, [currentSong.url])

  useEffectOnce(() => {
    if (currentSong) {
      const audioEl = audioRef.current!
      audioEl.src = currentSong.url
      audioEl.currentTime = currentTime
      audioEl.volume = volume
    }
  })

  useImperativeHandle(forwardedRef, () => ({
    prev,
    next,
    changeTime,
    changeVolume
  }))

  return (
    <audio
      ref={audioRef}
      onPause={pause}
      onCanPlay={ready}
      onError={error}
      onTimeUpdate={updateTime}
      onEnded={end}
    />
  )
}

export default forwardRef(Audio)

// client/vue3/src/components/Audio.vue
<script setup lang="ts">
import { PLAY_MODE } from '@/constant'
import { usePlayerStore } from '@/store/player'
import { equals } from '@/utils'
import { computed, onMounted, ref, watch } from 'vue'

// reactive
const audioRef = ref(null)
const isReady = ref(false)

// store
const playerStore = usePlayerStore()
const playList = computed(() => playerStore.playList)
const playing = computed(() => playerStore.playing)
const playMode = computed(() => playerStore.playMode)
const currentSong = computed(() => playerStore.currentSong)
const currentIndex = computed(() => playerStore.currentIndex)
const currentTime = computed(() => playerStore.currentTime)
const progressChanging = computed(() => playerStore.progressChanging)
const volume = computed(() => playerStore.volume)

onMounted(() => {
  if (currentSong.value) {
    const audioEl: HTMLAudioElement = audioRef.value!
    audioEl.src = currentSong.value.url
    audioEl.currentTime = currentTime.value
    audioEl.volume = volume.value
  }
})

// watch
watch(currentSong, (newSong, oldSong) => {
  if (!newSong.url) return
  if (equals(newSong, oldSong)) return

  isReady.value = false
  const audioEl: HTMLAudioElement = audioRef.value!
  audioEl.src = newSong.url
  audioEl.play()
})
watch(playing, (newPlaying) => {
  if (!isReady.value) return

  const audioEl: HTMLAudioElement = audioRef.value!
  newPlaying ? audioEl.play() : audioEl.pause()
})

// methods
const pause = () => {
  playerStore.setPlaying(false)
}
const ready = (e: Event) => {
  if (isReady.value) return
  isReady.value = true

  if (!currentSong.value.duration) {
    playerStore.$patch(state => {
      state.playList[state.currentIndex] = {
        ...currentSong.value,
        duration: (e.target as HTMLAudioElement).duration
      }
    })
  }
  playerStore.setVolume((e.target as HTMLAudioElement).volume)
}
const loop = () => {
  const audioEl: HTMLAudioElement = audioRef.value!
  audioEl.currentTime = 0
  playerStore.setPlaying(true)
}
const prev = () => {
  const list = playList.value
  if (!isReady.value || !list.length) return

  if (list.length === 1) {
    loop()
  } else {
    let index = currentIndex.value - 1
    if (index === -1) index = list.length - 1
    playerStore.setCurrentIndex(index)
    if (!playing.value) playerStore.setPlaying(true)
  }
}
const next = () => {
  const list = playList.value
  if (!isReady.value || !list.length) return

  if (list.length === 1) {
    loop()
  } else {
    let index = currentIndex.value + 1
    if (index === list.length) index = 0
    playerStore.setCurrentIndex(index)
    if (!playing.value) playerStore.setPlaying(true)
  }
}
const error = () => {
  isReady.value = true
}
const updateTime = (e: Event) => {
  if (progressChanging.value) return

  playerStore.setCurrentTime((e.target as HTMLAudioElement).currentTime)
}
const changeTime = (currentTime: number) => {
  (audioRef.value! as HTMLAudioElement).currentTime = currentTime
}
const end = () => {
  playerStore.setCurrentTime(0)

  if (playMode.value === PLAY_MODE.LOOP) {
    loop()
  } else {
    next()
  }
}
const changeVolume = (volume: number) => {
  (audioRef.value! as HTMLAudioElement).volume = volume
}

defineExpose({
  prev,
  next,
  changeTime,
  changeVolume
})
</script>

<template>
  <audio
    ref="audioRef"
    @pause="pause"
    @canplay="ready"
    @error="error"
    @timeupdate="updateTime"
    @ended="end"
  />
</template>
