// client/vue3-tsx/src/components/music-item/MusicItem.tsx
import { FolderDownload, Delete } from '@icon-park/vue-next'
import { computed, defineComponent, PropType, withModifiers } from 'vue'
import createToast from '../toast'
import './MusicItem.scss'
import { useMusicStore } from '@/store/musiclist'
import { usePlayerStore } from '@/store/player'
import { MusicItem } from '@/types'
import { STORAGE } from '@/utils/enums'

export default defineComponent({
  name: 'MusicItem',
  props: {
    musicItem: {
      type: Object as PropType<MusicItem>,
      required: true
    },
    currentTab: {
      type: Number as PropType<STORAGE>
    }
  },
  emits: ['click'],
  setup (props, { emit }) {
    // store
    const playerStore = usePlayerStore()
    const musicStore = useMusicStore()
    const currentSong = computed(() => playerStore.currentSong)
    const localMusics = computed(() => musicStore.localMusics)

    // computed
    const isActive = computed(() => {
      return props.musicItem.title === currentSong.value?.title &&
      props.musicItem.artist === currentSong.value?.artist
    })
    const inLocal = computed(() => {
      return !!localMusics.value.find(item => item.title === props.musicItem.title && item.artist === props.musicItem.artist)
    })

    // methods
    const addToLocal = () => {
      musicStore.addToLocal(props.musicItem)
      createToast({ text: '已添加到本地' })
    }
    const removeFromLocal = () => {
      musicStore.removeFromLocal(props.musicItem)
      createToast({ text: '移除成功' })
    }

    return () => (
      <div class={['music-item', isActive.value ? 'is-active' : '']} onClick={ () => emit('click') }>
        <div class="music-inner">
          <img
            v-lazy={ props.musicItem.cover }
            class="w-10 h-10"
            alt={ props.musicItem.title }
          />
          <span class="music-title ml-2.5 text-sm text-gray-800">{ props.musicItem.title }</span>
          <span class="music-artist mr-auto text-xs text-gray-500">
            <i class="mx-1.5">-</i>{ props.musicItem.artist }
          </span>
          {
            STORAGE.ONLINE === props.currentTab && !inLocal.value && (
              <FolderDownload
                class="p-2"
                theme="outline"
                size="16"
                fill="#333"
                onClick={ withModifiers(addToLocal, ['stop']) }
              />
            )
          }
          {
            STORAGE.LOCALE === props.currentTab && (
              <Delete
                class="p-2"
                theme="outline"
                size="16"
                fill="#333"
                onClick={ withModifiers(removeFromLocal, ['stop']) }
              />
            )
          }
        </div>
      </div>
    )
  }
})

// client/react/src/components/music-item/music-item.component.tsx
import { FC, MouseEventHandler } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { FolderDownload, Delete } from '@icon-park/react'
import LazyLoad from 'react-lazyload'

import { selectCurrentSong, selectMusicsReducer } from '@/store/selectors'
import { addToLocal, removeFromLocal } from '@/store/slices/musics'
import { STORAGE } from '@/utils/enums'
import { MusicItem as TMusicItem } from '@/types'

import './music-item.styles.scss'
import { useToast } from '../toast'

type MusicItemProps = {
  musicItem: TMusicItem
  currentTab: STORAGE
  onClick: () => void
}

const MusicItem: FC<MusicItemProps> = ({ currentTab, musicItem, onClick }) => {
  // context
  const toast = useToast()

  // selectors
  const { localMusics } = useSelector(selectMusicsReducer)
  const currentSong = useSelector(selectCurrentSong)
  const isActive =
    musicItem.title === currentSong?.title &&
    musicItem.artist === currentSong?.artist
  const inLocal = !!localMusics.find(
    (item) => item.title === musicItem.title && item.artist === musicItem.artist
  )

  // dispatch
  const dispatch = useDispatch()
  const _addToLocal: MouseEventHandler<HTMLSpanElement> = (event) => {
    event.stopPropagation()

    dispatch(addToLocal(musicItem))
    toast.open('已添加到本地')
  }
  const _removeFromLocal: MouseEventHandler<HTMLSpanElement> = (event) => {
    event.stopPropagation()

    dispatch(removeFromLocal(musicItem))
    toast.open('移除成功')
  }

  return (
    <div
      className={`music-item ${isActive ? 'is-active' : ''}`}
      onClick={onClick}
    >
      <div className="music-item-inner">
        <LazyLoad>
          <img
            src={musicItem.cover}
            className="w-10 h-10"
            alt={musicItem.title}
          />
        </LazyLoad>
        <span className="music-title ml-2.5 text-sm text-gray-800">
          {musicItem.title}
        </span>
        <span className="music-artist mr-auto text-xs text-gray-500">
          <i className="mx-1.5">-</i>
          {musicItem.artist}
        </span>
        {STORAGE.ONLINE === currentTab && !inLocal && (
          <FolderDownload
            className="p-2"
            theme="outline"
            size="16"
            fill="#333"
            onClick={_addToLocal}
          />
        )}
        {STORAGE.LOCALE === currentTab && (
          <Delete
            className="p-2"
            theme="outline"
            size="16"
            fill="#333"
            onClick={_removeFromLocal}
          />
        )}
      </div>
    </div>
  )
}

export default MusicItem
